name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Write .env.keys
        run: echo "DOTENV_PRIVATE_KEY_PROD=${{ secrets.DOTENV_PRIVATE_KEY_PROD }}" > .env.keys

      - name: Build & deploy
        run: |
          docker compose -f compose.prod.yml build
          docker compose -f compose.prod.yml up -d

      - name: Cleanup
        if: always()
        run: rm -f .env.keys
